apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parameterized-workflow-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: message
        value: "Default message"

  templates:
    - name: main
      steps:
        - - name: print-parameter
            template: echo

    - name: echo
      script:
        image: alpine:3.14
        command:
          - sh
        source: |
          echo "{{workflow.parameters.message}}"
